spring.application.name=TareaLab05

spring.datasource.url=jdbc:mysql://localhost:3306/lab6?serverTimezone=America/Lima&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
spring.messages.basename=messages
server.port=8080
